baseurl = "/"
languageCode = "en-us"
title = "HOXO-M Official Blog"
theme = "tuftesque"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "^docker-compose.yml$", "^Dockerfile$"]
relativeurls = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About Us"
    url = "http://hoxo-m.com"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/HOXOMInc"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/hoxom_inc"

[params]
    description = "Thus blog is written by a bunch of people who work on HOXO-M."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "python", "julia", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo_blog.png"
    width = 50
    height = 50
    alt = "Logo"
    
